src/Entity/Exchange.php
<?php

namespace App\Entity;

use App\Repository\ExchangeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: ExchangeRepository::class)]
class Exchange
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['agence:read'])]
    private ?int $id = null;

    #[ORM\Column(length: 5)]
    #[Groups(['agence:read'])]
    private ?string $FromCurrency = null;

    #[ORM\Column(length: 5)]
    #[Groups(['agence:read'])]
    private ?string $ToCurrency = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 15, scale: 2)]
    #[Groups(['agence:read'])]
    private ?string $FromAmount = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 15, scale: 2)]
    #[Groups(['agence:read'])]
    private ?string $ToAmount = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 5)]
    #[Groups(['agence:read'])]
    private ?string $taux = null;

    #[ORM\ManyToOne(inversedBy: 'exchanges')]
    #[ORM\JoinColumn(nullable: true)] 
    private ?Client $client = null;

    /**
     * @var Collection<int, AccountTransaction>
     */
    #[ORM\OneToMany(targetEntity: AccountTransaction::class, mappedBy: 'exchange', cascade: ['persist', 'remove'])]
    private Collection $transactions;

    #[ORM\ManyToOne(inversedBy: 'exchanges')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Agence $agence = null;

    #[ORM\Column(length: 255)]
    #[Groups(['agence:read'])]
    private ?string $Description = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['agence:read'])]
    private ?string $vanishClientName = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['agence:read'])]
    private ?string $VanishClientTel = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $date = null;

    #[ORM\Column(length: 10)]
    private ?string $type = null;

    public function __construct()
    {
        $this->transactions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFromCurrency(): ?string
    {
        return $this->FromCurrency;
    }

    public function setFromCurrency(string $FromCurrency): static
    {
        $this->FromCurrency = $FromCurrency;

        return $this;
    }

    public function getToCurrency(): ?string
    {
        return $this->ToCurrency;
    }

    public function setToCurrency(string $ToCurrency): static
    {
        $this->ToCurrency = $ToCurrency;

        return $this;
    }

    public function getFromAmount(): ?string
    {
        return $this->FromAmount;
    }

    public function setFromAmount(string $FromAmount): static
    {
        $this->FromAmount = $FromAmount;

        return $this;
    }

    public function getToAmount(): ?string
    {
        return $this->ToAmount;
    }

    public function setToAmount(string $ToAmount): static
    {
        $this->ToAmount = $ToAmount;

        return $this;
    }

    public function getTaux(): ?string
    {
        return $this->taux;
    }

    public function setTaux(string $taux): static
    {
        $this->taux = $taux;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): static
    {
        $this->client = $client;

        return $this;
    }

    /**
     * @return Collection<int, AccountTransaction>
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    public function addTransaction(AccountTransaction $transaction): static
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions->add($transaction);
            $transaction->setExchange($this);
        }

        return $this;
    }

    public function removeTransaction(AccountTransaction $transaction): static
    {
        if ($this->transactions->removeElement($transaction)) {
            // set the owning side to null (unless already changed)
            if ($transaction->getExchange() === $this) {
                $transaction->setExchange(null);
            }
        }

        return $this;
    }

    public function getAgence(): ?Agence
    {
        return $this->agence;
    }

    public function setAgence(?Agence $agence): static
    {
        $this->agence = $agence;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getVanishClientName(): ?string
    {
        return $this->vanishClientName;
    }

    public function setVanishClientName(?string $vanishClientName): static
    {
        $this->vanishClientName = $vanishClientName;

        return $this;
    }

    public function getVanishClientTel(): ?string
    {
        return $this->VanishClientTel;
    }

    public function setVanishClientTel(?string $VanishClientTel): static
    {
        $this->VanishClientTel = $VanishClientTel;

        return $this;
    }

    public function getDate(): ?\DateTimeImmutable
    {
        return $this->date;
    }

    public function setDate(?\DateTimeImmutable $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }
}

src/Controller/ExchangeController.php
<?php

namespace App\Controller;

use App\Entity\AccountTransaction;
use App\Entity\Agence;
use App\Entity\Exchange;
use App\Repository\AgenceRepository;
use App\Repository\ExchangeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class ExchangeController extends AbstractController
{
    #[Route('/dashboard/exchange', name: 'app_exchange')]
    public function index(): Response
    {
        return $this->render('exchange/index.html.twig', [
            'controller_name' => 'ExchangeController',
            'agences' => [],
            'clients' => [],
        ]);
    }

    #[Route('/api/exchanges', name: 'api_exchange_index', methods: ['GET'])]
    public function APIindex(Request $request, ExchangeRepository $repository, AgenceRepository  $agenceRepository): JsonResponse
    {

        $agenceId = $request->request->get('agence');
        $agence = $agenceRepository->findOneBy(['id' => $agenceId]);

        $filters = [
            'type' => $request->query->get('type'),
            'agence' => $agence,
            'startDate' => $request->query->get('startDate'),
            'endDate' => $request->query->get('endDate'),
        ];

        $exchanges = $repository->findByFilters($filters);

        $data = array_map(function ($exchange) {
            return [
                'id' => $exchange->getId(),
                'type' => $exchange->getType(),
                'client' => $exchange->getVanishClientName(),
                'clientPhone' => $exchange->getVanishClientTel(),
                'agence' => [
                    'id' => $exchange->getAgence()->getId(),
                    'name' => $exchange->getAgence()->getDesignation(),
                    'devise' => $exchange->getAgence()->getDevise(),
                    // Ajoutez d'autres propriétés de l'agence nécessaires
                ],
                'date' => $exchange->getDate()->format('Y-m-d'),
                'fromAmount' => ($exchange->getType() == "achat") ? $exchange->getFromAmount() : $exchange->getToAmount(),
                'toAmount' => ($exchange->getType() == "achat") ? $exchange->getToAmount() : $exchange->getFromAmount(),
                'taux' => $exchange->getTaux(),
                'fromCurrency' => ($exchange->getType() == "achat") ? $exchange->getFromCurrency() : $exchange->getToCurrency(),
                'toCurrency' => ($exchange->getType() == "achat") ? $exchange->getToCurrency() : $exchange->getFromCurrency(),
                // Ajoutez d'autres propriétés de l'échange nécessaires
            ];
        }, $exchanges);

        return new JsonResponse(['data' => $data]);
    }

    #[Route('/api/exchanges', name: 'api_exchange_create', methods: ['POST'])]
    public function create(Request $request, EntityManagerInterface $em): JsonResponse
    {
        // 1. Récupérer et valider l'agence
        $agenceId = $request->request->get('agence');
        $agence = $em->getRepository(Agence::class)->find($agenceId);
        if (!$agence) {
            return new JsonResponse(['error' => 'Agence introuvable'], Response::HTTP_BAD_REQUEST);
        }

        // 2. Récupérer les données de la requête
        $clientNom = $request->request->get('clientNom');
        $clientPhone = $request->request->get('clientPhone');
        $date = $request->request->get('date');
        $montant = (float) $request->request->get('montant');
        $taux = (float) $request->request->get('taux');
        $type = $request->request->get('type');

        // 3. Déterminer les devises selon le type d'échange
        $fromCurrency = ($type === 'achat') ? 'CFA' : $agence->getDevise();
        $toCurrency = ($type === 'achat') ? $agence->getDevise() : 'CFA';

        $fromAmount = ($type === 'achat') ?  $montant * $taux : $montant; 
        $toAmount = ($type === 'achat') ? $montant : $montant * $taux ; 

        // 4. Créer l'échange
        $exchange = new Exchange();
        $exchange->setAgence($agence);
        $exchange->setVanishClientName($clientNom);
        $exchange->setVanishClientTel($clientPhone);
        $exchange->setDate(new \DateTimeImmutable($date));
        $exchange->setFromAmount($fromAmount);
        $exchange->setFromCurrency($fromCurrency);
        $exchange->setToCurrency($toCurrency);
        $exchange->setToAmount($toAmount);
        $exchange->setTaux($taux);
        $exchange->setType($type);
        $exchange->setDescription('');

        // 5. Générer une référence de paiement unique
        $ref_payment = uniqid('EXCH_', false);

        // 6. Créer les transactions associées
        // Transaction de retrait
        $withdrawalTx = new AccountTransaction();
        $withdrawalTx->setClient(null) // À remplacer par la logique pour récupérer le client si nécessaire
            ->setIncome(0)
            ->setOutcome($fromAmount)
            ->setDevise($fromCurrency)
            ->setAccountType('local')
            ->setUpdatedAt(new \DateTimeImmutable())
            ->setReason("Échange de $fromCurrency à $toCurrency")
            ->setDescrib("Achat de $toCurrency")
            ->setPaymentRef($ref_payment)
            ->setStatus('validé')
            ->setCreatedAt(new \DateTimeImmutable())
            ->setPaymentMethod('Exchange')
            ->setExchange($exchange);

        // Transaction de dépôt
        $depositTx = new AccountTransaction();
        $depositTx->setClient(null) // À remplacer par la logique pour récupérer le client si nécessaire
            ->setIncome($toAmount)
            ->setOutcome(0)
            ->setDevise($toCurrency)
            ->setAccountType('local')
            ->setUpdatedAt(new \DateTimeImmutable())
            ->setReason("Échange de $fromCurrency à $toCurrency")
            ->setDescrib("Vente de $fromCurrency")
            ->setPaymentRef($ref_payment)
            ->setStatus('validé')
            ->setCreatedAt(new \DateTimeImmutable())
            ->setPaymentMethod('Exchange')
            ->setExchange($exchange);

        // 7. Persister et sauvegarder en base de données
        $em->persist($exchange);
        $em->persist($withdrawalTx);
        $em->persist($depositTx);
        $em->flush();

        // 8. Retourner la réponse
        return new JsonResponse([
            'id' => $exchange->getId(),
            'type' => $exchange->getType(),
            'agence' => $exchange->getAgence()->getId(),
            'date' => $exchange->getDate()->format('Y-m-d H:i:s'),
            'fromAmount' => $exchange->getFromAmount(),
            'fromCurrency' => $exchange->getFromCurrency(),
            'toAmount' => $exchange->getToAmount(),
            'toCurrency' => $exchange->getToCurrency(),
            'taux' => $exchange->getTaux(),
        ], Response::HTTP_CREATED);
    }


    #[Route('/api/exchanges/{id}/validate', name: 'api_exchange_validate', methods: ['PUT'])]
    public function validate(Exchange $exchange, EntityManagerInterface $em): JsonResponse
    {
        foreach ($exchange->getTransactions() as $transaction) {
            $transaction->setStatus('completed');
            $transaction->setValidateAt(new \DateTimeImmutable());
        }

        $em->flush();
        return new JsonResponse(['status' => 'Échange validé'], Response::HTTP_OK);
    }

    #[Route('/api/exchanges/{id}/cancel', name: 'api_exchange_cancel', methods: ['PUT'])]
    public function cancel(Exchange $exchange, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $reason = $request->request->get('reason', 'Annulé par l\'utilisateur');

        foreach ($exchange->getTransactions() as $transaction) {
            $transaction->setStatus('cancelled');
            $transaction->setReason($reason);
        }

        $em->flush();
        return new JsonResponse(['status' => 'Échange annulé'], Response::HTTP_OK);
    }

    #[Route('/api/exchanges/{id}', name: 'api_exchange_delete', methods: ['DELETE'])]
    public function delete(Exchange $exchange, EntityManagerInterface $em): JsonResponse
    {
        $em->remove($exchange);
        $em->flush();

        return new JsonResponse(null, Response::HTTP_NO_CONTENT);
    }

    #[Route('/api/exchanges/{id}/print', name: 'api_exchange_print', methods: ['GET'])]
    public function Print(Exchange $exchange, EntityManagerInterface $em): Response
    {
        return $this->render('exchange/print.html.twig', [
            'controller_name' => 'ExchangeController',
            'exchange' => $exchange
        ]);
    }

    #[Route('/api/exchanges/stats', name: 'api_exchange_stats', methods: ['GET'])]
    public function stats(ExchangeRepository $repository, Request $request): JsonResponse
    {
        $startDate = $request->query->get('startDate');
        $endDate = $request->query->get('endDate');
        $agenceId = $request->query->get('agence');

        $filters = [
            'startDate' => $startDate,
            'endDate' => $endDate,
            'agence' => $agenceId,
        ];

        $exchanges = $repository->findByFilters($filters);

        $total = count($exchanges);
        $completed = 0;
        $pending = 0;
        $cancelled = 0;
        $achat = 0;
        $vente = 0;
        $montantAchat = 0;
        $montantVente = 0;
        $tauxSum = 0;

        foreach ($exchanges as $exchange) {
                    $completed++;
            

            if ($exchange->getType() === 'achat') {
                $achat++;
                $montantAchat += $exchange->getFromAmount();
            } else {
                $vente++;
                $montantVente += $exchange->getToAmount();
            }

            $tauxSum += $exchange->getTaux();
        }

        $tauxMoyen = $total > 0 ? round($tauxSum / $total, 2) : 0;

templates/exchange/print.html.twig
{# templates/exchange_receipt.html.twig #}
<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>Reçu d'Échange</title>
		<style>
			@page {
				size: A5 landscape;
				margin: 30px;
			}

			body {
				font-family: Arial, sans-serif;
				font-size: 14px;
				margin: 0;
				padding: 0;
			}

			/* En-tête */
			.header {
				display: flex;
				justify-content: space-between;
				align-items: flex-start;
				margin-bottom: 10px;
			}
			.header img {
				width: 128px;
				height: auto;
			}
			.company-info {
				text-align: right;
				font-size: 12px;
			}

			/* Titre centré */
			.title {
				text-align: center;
				font-size: 26px;
				font-weight: bold;
				margin: 10px 0 20px;
				text-transform: uppercase;
			}

			/* Cadres */
			.content {
				display: flex;
				gap: 0;
				height: calc(100% - 150px); /* laisser place au header + footer */
			}

			.box {
				flex: 1;
				border: 3px solid black;
				padding: 15px;
				display: flex;
				flex-direction: column;
				justify-content: space-evenly;
				font-size: 18px;
                height: 250px;
			}

			.box span {
				font-weight: bold;
			}

			/* Footer */
			.footer {
				display: flex;
                justify-content: space-between;
				margin-top: 20px;
                margin-left: 20px; 
                margin-right: 20px;
				font-size: 12px;
			}
		</style>
	</head>
	<body>

		<!-- En-tête -->
		<div class="header">
			<div class="logo">
				<img src="{{ asset('assets/img/logo.png') }}" alt="Logo">
			</div>
			<div class="company-info">
				<small>Billeterie-Change-Transaction-Commerce Général</small><br><br>
				BKO IMM. PETIT BAROU<br>
				Tél: (+223) - 66626317 - 76260611<br>
				DUBAI: (+971) - 55 426 2144
			</div>
		</div>

		<!-- Titre -->
		<div class="title">
			REÇU D'ÉCHANGE DE DEVISES
			<br>
			<small>{{ exchange.description }}</small>
		</div>


		<!-- Contenu principal -->
		<div
			class="content">
			<!-- Cadre gauche -->
			<div class="box">
				<div>Opération :
					<span>{{ exchange.agence ? exchange.type : 'Echange compte client' }}</span>
				</div>
                <div>Date :
                    <span>{{ exchange.date ? exchange.date|date('d/m/Y') : '' }}</span>
                </div>
				<div>Nom Client :
					<span>{{ exchange.client ? exchange.client.nom : exchange.vanishClientName }}</span>
				</div>
				<div>Téléphone :
					<span>{{ exchange.client ? exchange.client.phone : exchange.vanishClientTel  }}</span>
				</div>
				<div>Destination :
					<span>{{ exchange.agence ? exchange.agence.localite : '--'  }}</span>
				</div>
			</div>

			<!-- Cadre droit -->
			<div class="box">
				{% if exchange.agence %}
					<div>Montant CFA :
						<span>{{ exchange.type == "achat" ? exchange.fromAmount : exchange.toAmount }}
							{{ exchange.type == "achat" ? exchange.fromCurrency : exchange.toCurrency }}</span>
					</div>
					<div>Montant Devise :
						<span>{{ exchange.type == "achat" ? exchange.toAmount : exchange.fromAmount }}
							{{ exchange.type == "achat" ? exchange.toCurrency : exchange.fromCurrency }}</span>
					</div>
				{% else %}
					<div>Montant Vendu :
						<span>{{ exchange.fromAmount }}
							{{ exchange.fromCurrency }}</span>
					</div>
					<div>Montant Acheté :
						<span>{{ exchange.toAmount }}
							{{ exchange.toCurrency }}</span>
					</div>
				{% endif %}
				<div>Taux appliqué :
					<span>{{ exchange.taux }}</span>
				</div>
			</div>
		</div>

		<!-- Footer -->
		<div class="footer">
            <span>Signature Client</span>
            <small>Merci pour votre confiance !</small>
			<span>Délivré par : MOUSSA TIGANA</span>
            
		</div>

		<script>
			window.addEventListener('load', function() {
            setTimeout(function() {
                window.print();
                // Fermer après impression si dans un nouvel onglet
                setTimeout(function() { window.close(); }, 500);
            }, 500);
        });
		</script>
	</body>
</html>